### ISSUE TITLE
Excel to CSV: including sheet name as column lacks header

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#360]
When the Excel to CSV component's "Include sheet name as additional column" option is switched on, an additional column named `sheet_name` should be added with the value of the sheet name (as per [documentation](http://etl.linkedpipes.com/components/t-exceltocsv)). However, when this option is used, the component add the value of the sheet name without the column header `sheet_name`. Instead, the actual sheet name is used in place of `sheet_name`.

Tested using the develop version 9a42adc02da86a8cdc00bfa6fdd45ac09f568a05.

**Comment by skodapetr** [comment]
@jindrichmynarz This is expected behaviour if option "Virtual column with header" is unchecked. If checked the table is assumed to have header and thus "sheet_name" is added to the header. Otherwise it's assume there is no header so the sheet name is used in the first row. 

Could you please check whether this option is checked? If not it may be an issue of unclear documentation?

**Comment by jindrichmynarz** [comment]
Since the [documentation](http://etl.linkedpipes.com/components/t-exceltocsv) says "Virtual columns have header: TODO - do not use now", I did not use this switch. When switched on, the component adds `sheet_name` into the first output row, as expected.

So this is an issue of missing documentation.
