### ISSUE TITLE
Download without credentials is missing templates

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#382]
When a pipeline is downloaded without credentials and loaders use templates, the templates are missing in the download.

E.g. https://etl.nkod.opendata.cz/resources/pipelines/created-1494913343620

**Comment by skarampatakis** [comment]
We have the same problem probably with this pipeline.

https://github.com/openbudgets/pipeline-fragments/blob/master/CSV2RDF/pipeline/CSV2OBEURDF-Template.jsonld

What is the status of this issue. I managed to workaround this issue by changing manually the template component url, but I think that it worked because the template was already available on my LP instance. I am not sure what would be the behavior if it didn't exist.

**Comment by skodapetr** [comment]
@skarampatakis Have you exported the pipeline by the "Download without credentials" from the pipeline list screen?

**Comment by skarampatakis** [comment]
I am not aware how this pipeline was downloaded as it was sent to me from other people. I will ask and inform.

**Comment by skodapetr** [comment]
@skarampatakis Thanks, could you also please ask them (just to be sure) if the missing template exists on the source machine?

**Comment by skarampatakis** [comment]
The template exists, but since it uses a different URI my understanding says that the executor cannot find it probably? As I said above every URI is successfully rewritten to match the LP instance domain, except those referring a template. I managed to bypass the problem by manually edit the template URI. Both me and the pipeline creator use the same LP instance.

**Comment by skarampatakis** [comment]
correction: It seems that the pipeline template on https://github.com/openbudgets/pipeline-fragments/blob/master/CSV2RDF/pipeline/CSV2OBEURDF-Template.jsonld was downloaded with the without credentials method, so it probably misses the template as said above. I tried to upload the pipeline to a different instance without any modification and got the missing component error. Then I downloaded the pipeline template with the normal download button and successfully uploaded the pipeline without any errors. 

So it seems to be the same issue as @jakubklimek mentions.

**Comment by jakubklimek** [comment]
With @skodapetr we agreed on the following:
In pipeline editor menu, there will be these options:
1. Offline backup (without templates) - saves current state of the pipeline in the editor. Useful e.g. when Internet connection is down and one wants to save the current work in a file.
2. Save and download: Needs internet connection to the server. Saves the current state and downloads the pipeline, including templates. Same as "Download" from Pipelines menu
3. Save and download without credentials: Same as 2., only without credentials.

**Comment by jakubklimek** [comment]
Download backup => Offline backup, and move it to be the third option, not the first one.

**Comment by jakubklimek** [comment]
In addition, in the "without credentials" option, the output file is named "XXX.jsonld.jsonld" (twice jsonld extension)
