### ISSUE TITLE
Enhancement: Docker image

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#414]
It would be useful to have an "official" Docker image for LP-ETL to ease its deployment. This can be based on the image done for [OpenBudgets.eu](https://github.com/openbudgets/integration/tree/master/docker-config/linkedpipes).

**Comment by jakubklimek** [comment]
When implementing. also consider https://github.com/linkedpipes/etl/pull/627

**Comment by rizktouma** [comment]
Are there any updates on this issue? I am trying to deploy LinkedPipes and execute my pipelines in a container and it would be very helpful to have an official docker image (or maybe some tips on how to build one).

**Comment by jakubklimek** [comment]
@rizktouma It is in our pipeline for this year. Meanwhile, you can gen inspired by #627

**Comment by rizktouma** [comment]
@jakubklimek thanks for the tip. I've been dabbling with this the last couple of days and I've managed to run a docker containing all 4 services of LP (based on the dockerfile in the issue you mentioned).

I'm having some problems with already-existing pipelines though. It seems like the "domain.uri" property in the configuration file MUST match the URL on which the frontend of LP is running. The same seems to apply to the definitions of templates (otherwise, the frontend won't load them correctly).

Is this meant to be that way or is it just something that wasn't considered?

**Comment by jakubklimek** [comment]
@rizktouma this is on purpose. As everything in Linked Data, the pipelines and templates are identified by their IRIs. A migration guide is available here in the Wiki

**Comment by skodapetr** [comment]
docker-compose one-line command:
```
sudo curl https://raw.githubusercontent.com/linkedpipes/etl/develop/docker-compose.yml | sudo LP_ETL_PORT=9080 LP_ETL_DOMAIN=http://localhost:9080 LP_ETL_BUILD_BRANCH=develop docker-compose -f - up
```

If other changes need to be done a change in configuration is required.
Further issues and comments should be resolved in other issues as this one is a little older.
