### ISSUE TITLE
Files to RDF chunked doesn't use its input's namespace prefixes

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#417]
Files to RDF chunked doesn't use its input's namespace prefixes, so that when the data is serialized again, there no compact IRIs are used. It would be better if the prefixes were retained.

Tested using the develop version a7735c76d568bbe999a4ada6750f97f7556d8f39.

**Comment by skodapetr** [comment]
The "chunked RDF" is an inner representation. Which component do you use to serialise the data back to output RDF, what is the use case ? 

Implementation of this would mean that the chunked RDF (why not also RDF dataunits? ) would carry not only RDF data but also information about used prefixes. So those prefixes could be used once the RDF is serialised back. In order to this to work properly every (chunked) RDF component would need to support that - including SPARQL query components.

**Comment by jindrichmynarz** [comment]
I use Chunked RDF to file to serialize the data.

**Comment by skodapetr** [comment]
@jakubklimek Do we want to somehow handle this, or should this be resolved by providing user a way how to specify used prefixes in t-t-filesToRdfChunked .

**Comment by jakubklimek** [comment]
If this is a simple matter of adding a textbox for "turtle-style" prefix definition, I would add it.
