### ISSUE TITLE
Enhancement: throw an error if invalid configuration is passed in

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#448]
Since input ports are distinguished only by colour (#394), it sometimes happens to me that I drag an RDF input to the configuration port instead of the data port, e.g., of the SPARQL CONSTRUCT component. When such pipeline is run, it runs without problems. It only typically produces no output, since there is no input data. It would be helpful if LP-ETL detected an invalid configuration (e.g., by validating configuration via SHACL, Java library [here](https://github.com/TopQuadrant/shacl)) and threw an error.

Tested using the develop version 38e09fb30bd3cf08b802c1ec29196091cceddeaa.

**Comment by skodapetr** [comment]
I'm not sure how to defined and invalid configuration.

The configuration input may contains other data (as it can be used to configure several components at once), so it is not possible to throw an exception if there are other data or other properties on the configuration class. 

Also if there is a configuration class we can't really throw if there are properties missing (for example due to a typ query -> quary ) as all predicates are obligatory. This for for the use-case when the user want to set (override) only certain parts of the configuration.

We also can not easily check for configuration entity. The component does not recognise whether there is something connected to the configuration port. But even if we change this (and the component can detect if something is connected to input) user may still decide not to provide the configuration and use default. A use case can be where the configuration is taken from the pipelineInput component - ie. it is  specified as input to the execution.


What seems to me like a more realistic approach would be to employ some "quality-like" components/extensions which can check for empty output.

**Comment by jindrichmynarz** [comment]
An easy check would be to detect if no instance of the configuration class is provided. For example, for the SPARQL CONSTRUCT component:

```sparql
ASK { [] a <http://plugins.linkedpipes.com/ontology/t-sparqlConstruct#Configuration> .
```

I think the only approach when this would not work is when the configuration is provided dynamically and there is a default configuration filled in the component. However, I don't know if this is not only a theoretical possibility.

**Comment by skodapetr** [comment]
@jakubklimek @jindrichmynarz But the component does not recognise if the configuration dataunit is connected to something or not. So just adding a check for configuration dataunit would result in failure of every component without provided runtime configuration. 
We could implement a check for the connection followed by the check for the configuration class, still we need to consider the possibility of dynamic configuration. This can happen for a pipeline which is executed with input (e-pipelineInput) and use the input to provide user with a possibility to override default configuration of component.

**Comment by jakubklimek** [comment]
I'd say that missing configuration on configuration input is not an invalid state and should not raise errors. It simply means that the component has nothing to do in this execution.

**Comment by jindrichmynarz** [comment]
@jakubklimek, the original issue is not about missing configuration, it is about helping to detect that the user has mistakenly connected input data as configuration.

**Comment by jakubklimek** [comment]
OK, but there is no way to do it, as this is a legitimate thing to do.

**Comment by jindrichmynarz** [comment]
Legitimate? The mistakenly connected data would likely not be a valid configuration.

**Comment by jakubklimek** [comment]
Yes. And therefore, nothing would be done. It may also happen that you connect something which generates tasks only sometimes, depending on the inputs.

**Comment by jindrichmynarz** [comment]
OK, the dynamic aspect of configuration makes this difficult to solve. Then I think preventing this from happening is up to #394.
