### ISSUE TITLE
FTP browser: authentication required

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#454]
For some reason the FTP browser of intermediate data produced by the components requires authentication for HTML files or their subset. This issue can be replicated by using this [sample pipeline](https://github.com/linkedpipes/etl/files/1169787/Test.protected.FTP.jsonld.zip). It only has an HTML file in the Text holder. Run it and try to view the output of the Text holder by following its link. You will see a request for authentication:

<img width="387" alt="screen shot 2017-07-24 at 14 25 59" src="https://user-images.githubusercontent.com/198642/28523316-24854086-707c-11e7-95c0-ee76a5a1ae5d.png">

Tested using the develop version 622aca9c523d66f65d381b4fa4e3f08b7f0d9a90.

**Comment by skodapetr** [comment]
Well the problem is that the browser open the FTP file as a HTML page. Now the behaviour is different for IE, FireFox and Chrome. 

For Chrome: 
The basic problem is that there is a limit to anonymous logins and logins in general (default to 10) in the used FTP server implementation. In order to speed up page loading the Chrome opens multiple connections, for each connection it tries to log in - exceeding the maximum number anonymous logins (general logins). This cause FTP server to ask for credentials. 

However even if the login limit is increased there are exceptions with passive mode - there is just no authorisation request in that case. 

This is not an issue with "proper" FTP clients (Filezilla), which just transfer the file.

The maximum number of logins may be connected to #451.

**Comment by jakubklimek** [comment]
Seems to be an issue of inconsistent FTP clients - outside of LP-ETL.

**Comment by jindrichmynarz** [comment]
How about switching from FTP to HTTP for accessing the debug data? That would avoid these problems.

**Comment by jakubklimek** [comment]
Debug data are files. FTP is for files, HTTP is for text... Bulk downloading of larger number of files would become harder.

**Comment by jindrichmynarz** [comment]
Sure, FTP may be better suited for handling files, but if there are such problems with it, then I see no reason not use HTTP, which can handle a superset of FTP's functionality. What would become harder for bulk download of multiple files? Do you mean that now you can connect with a FTP client and copy an arbitrary number of files by just drag and drop?

**Comment by jakubklimek** [comment]
Yes, exactly. And I had no problems until recently.
