### ISSUE TITLE
Expected handling of OutOfMemoryError?

### ISSUE THREAD

**Issue by jindrichmynarz** [linkedpipes/etl#467]
When the executor encounters `java.lang.OutOfMemoryError: Java heap space`, the execution is stopped, but the front-end still indicates that the pipeline that caused the error is running. This persists in the front-end also after refresh. Is that the expected handling of OutOfMemoryError? I would assume that if the executor is able to sustain an OutOfMemoryError, then it should notify the front-end that the pipeline failed.

Tested using the develop version a75fb28f7ad8645d4beb9d1d56baf37472640ee5.

**Comment by skodapetr** [comment]
Do you have the execution, or the pipeline? 
I update TextHolder to cause OutOfMemoryError and pipeline failed properly with in the TextHolder with:

Cause: 
Component execution failed.
Root cause: 
OutOfMemoryError : Java heap space

However I can imagine this can be different if the exception happen outside the component.

**Comment by jindrichmynarz** [comment]
No, I no longer have the execution. The error happened when the SPARQL CONSTRUCT to file list was executing. However, I assume the higher-level exception handling is the same for all components.

**Comment by skodapetr** [comment]
Yes the handling of exceptions for all components is the same. Should that happen again we will reopen the issue with particular execution that fail - so we can reproduce and fix the issue.
