### ISSUE TITLE
Improve invalid IRI handling

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/etl#653]
See [this execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1546867703762&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1546867732987-307-1b1b10be-a824-40f8-ba0c-32614d29dc79). The input file contains invalid IRIs (of various kinds). The same errors are in the results which we get using the sparql endpoint extractor with "escape invalid IRIs".

The source of the data is EDP's Virtuoso Endpoint.

1. The original Sparql endpoint extractor, and the Sparql Endpoint Chunked used [here](https://etl.opendata.cz/#/pipelines/edit/canvas?pipeline=https:%2F%2Fetl.opendata.cz%2Fresources%2Fpipelines%2Fcreated-1496828127317) have an "Escape invalid IRI" switch, which, however, does not work here.
2. Files to RDF Single Graph used in the linked pipeline does not have this option at all.

To be able to work with this kind of errorneous data, we need to investigate whether it is possible to do a more robust invalid IRI escaping, primarily when accessing remote endpoints.

**Comment by skodapetr** [comment]
This is caused by 
```
<http://europeandataportal.eu/set/record/2f3290c3-4ce5-b904-5cc7-49381a2185d8> <http://www.w3.org/ns/adms#status>
    <:modified> .
```
that rdf4j Turtle and N-Triples parsers fail to parse. 
We can try to use other formats (json-ld) that are able to handle that.

**Comment by skodapetr** [comment]
Unfortunately, it seems that the part that needs to be modified is not easily accessible via inheritance.

We would need to create almost a copy of the SPARQL repository functionality in order to use custom parsers (that can somehow deal with that) that can handle this issue.

At one point it seems that it would be possible to supply custom ParserConfiguration but that would need further exploration.
