### ISSUE TITLE
Unable to compile latest master nor develop

### ISSUE THREAD

**Issue by eghuro** [linkedpipes/etl#681]
Build is failing with
`[ERROR] Failed to execute goal on project x-virtuoso: Could not resolve dependencies for project com.linkedpipes:x-virtuoso:bundle:0.0.0: Failed to collect dependencies at com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Failed to read artifact descriptor for com.openlinksw.virtuoso:virt_rdf4j:jar:20170111: Could not transfer artifact com.openlinksw.virtuoso:virt_rdf4j:pom:20170111 from/to artefacts.linkedpipes.com (https://artefacts.linkedpipes.com/repository/maven-public/): Failed to transfer file https://artefacts.linkedpipes.com/repository/maven-public/com/openlinksw/virtuoso/virt_rdf4j/20170111/virt_rdf4j-20170111.pom with status code 502 -> [Help 1]
`

**Comment by jakubklimek** [comment]
The server hosting the artefact is down atm (the Sonatype Nexus hosting the artefact got hacked and was mining crypto). We will reinstall tomorrow.

**Comment by jakubklimek** [comment]
Actually, you may try now

**Comment by jakubklimek** [comment]
OK, this was a [known security issue CVE-2019-7238](https://support.sonatype.com/hc/en-us/articles/360017310793-CVE-2019-7238-Nexus-Repository-Manager-3-Missing-Access-Controls-and-Remote-Code-Execution-February-5th-2019?_ga=2.233022810.558744858.1555266395-998947440.1555266395) - should be fixed by the update.

**Comment by eghuro** [comment]
It works now! Thanks.
