### ISSUE TITLE
t-sparqlupdate component fails for specific file with SPARQL LOAD command

### ISSUE THREAD

**Issue by gkostkowski** [linkedpipes/etl#919]
Hi!
Thank you for your effort, ETL tool is very useful.

I found an issue related with `t-sparqlupdate` component. As I see, SPARQL LOAD command in query is supported, but it doesn't work for some files. I prepared demo pipeline with two components (files), the first one throws following exception:
```
NullPointerException : Cannot invoke "String.indexOf(int)" because "mimeType" is null
```

[online pipeline demonstrating the issue](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1650360302385&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1650360436487-1833-cbfd30dd-7a18-4a7c-88ef-3b4b5b913d50)

**Comment by jakubklimek** [comment]
Hello, thanks for the feedback.
First of all, to be honest, I never used the `t-sparqlUpdate` with `SPARQL LOAD` - for an equivalent effect, I would use something like [this execution](https://demo.etl.linkedpipes.com/#/pipelines/edit/canvas?pipeline=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fpipelines%2F1650363705896&execution=https:%2F%2Fdemo.etl.linkedpipes.com%2Fresources%2Fexecutions%2F1650363731191-1834-e7250753-e687-4896-b9ab-1cb5836d6090) - splitting the network access and the actual loading in two steps.

That being said, the error actually describes the problem quite well. Accessing the resource in question using curl: `curl -I -v https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/2021/void_1.0.0.ttl` we can see that there is no `Content-Type` HTTP header present (probably bad web server configuration). Eclipse rdf4j (the underlying RDF library) depends on the `Content-Type` header to determine which RDF serialization is being used in order to load it.

With `curl -I -v https://www.eionet.europa.eu/gemet/void.rdf` the content type is `text/xml` - also incorrect, it should be `application/rdf+xml` but I guess since there is only one XML-based serialization of RDF, some kind of fallback behavior takes effect here.

**Comment by gkostkowski** [comment]
Thank you for the answer. I prefer query with LOAD over solution with x-httprequest as it is a bit more concise (it makes a difference when dealing with many occurences). Anyway, I will use method with x-httprequest and t-filestordfsinglegraph as in this case I can control the format and avoid such issues with input files.
