### ISSUE TITLE
Malformed Content Type Header for POST requests with x-httpRequest

### ISSUE THREAD

**Issue by mnmercer** [linkedpipes/etl#943]
When executing a POST request with x-httpRequest with a file input, the Content-Type header is malformed because of an extra character in the boundary definition. The offending line is [line 21](https://github.com/linkedpipes/etl/blob/475829cb569d8946d1aeb7a14c2353e73d68a1cb/plugins/x-httpRequest/src/main/java/com/linkedpipes/plugin/exec/httprequest/MultipartConnection.java#L21) in `plugins/x-httpRequest/src/main.java/com/linkedpipes/plugin/exec/httprequest/MultipartConnection.java`. It currently looks like
```
this.boundary = "=----------------------" + System.currentTimeMillis();
```
When it should be
```
this.boundary = "----------------------" + System.currentTimeMillis();
```
I tried to create a PR with this small change, but I don't appear to have permissions to push a new branch to the repo.

**Comment by skodapetr** [comment]
@mnmercer You need to fork this repository. Do the update, in your repository, and then create a PR.

Although I could fix this myself, I want to give you some time (three days from now) to do the PR. The reason is that  you did a great job in identifying the source of the problem, and I believe it would be nice to give you a credit using the PR for fixing the issue.
